version: "3.8"
services:
    database:
        hostname: laragento-db
        container_name: laragento-db
        image: mysql:5.7-debian
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
volumes:
    db:
